server:
  address: localhost
  port: 9000
  servlet:
    context-path: /api/v1

spring:
  application: finace-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance_manager_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true