server:
  address: localhost
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application: finance-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/finance_manager_db}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:129dsd04281dj4103c01u1nxzj1x29123hxxkl123masdash3gu1fyh2dvk23mkm122}
    access: ${SECURITY_JWT_ACCESS_EXPIRED:3600000}
    shared: ${SECURITY_JWT_ACCESS_EXPIRED:3600000}
    refresh: ${SECURITY_JWT_REFRESH_EXPIRED:2592000000}